# configuration file

# Site settings
locale: en_US
title: Lorenzo Pessina
email: l.pessina@columbia.edu
subtitle: PhD Candidate in Economics
description: Lorenzo Pessina website economics
url : https://lorenzopessina.github.io
repository: lorenzopessina/lorenzopessina.github.io
# logo: "assets/images/columbia_logo.jpg"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.5"
minimal_mistakes_skin: "air" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  
# author
author :
  name: Lorenzo Pessina
  avatar: "assets/images/Pessina_1.jpg"
  bio: PhD Candidate in Economics at Columbia University
  location: New York, NY
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lorenzopessina"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/laurenz_pss"
    
  